DROP TABLE vote_board IF EXISTS;
DROP TABLE user_roles if EXISTS ;
DROP TABLE users IF EXISTS;
DROP SEQUENCE GLOBAL_SEQ IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(   id           INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name         VARCHAR(255)       NOT NULL,
    email        VARCHAR(255)       NOT NULL,
    password     VARCHAR(255)       NOT NULL
);

CREATE TABLE user_roles
(   user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_role_unique UNIQUE (user_id,role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE vote_board
(   id           INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    restaurant      VARCHAR(255)                    NOT NULL,
    dish            VARCHAR(255)                    NOT NULL,
    dish_price      NUMERIC                         NOT NULL,
    date_time       TIMESTAMP  DEFAULT now()        NOT NULL,
    vote            BOOLEAN                         NULL,
    user_id         INTEGER                         NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
--       CONSTRAINT user_vote_unique UNIQUE (restaurant, user_id,vote)
);

